#ifndef PARSER_HPP
#define PARSER_HPP

#include <string>

#include "antlr4-runtime.h"
#include "automata/nfa/lva.hpp"
#include "visitors.hpp"
#include "parse/grammar/autogenerated/REmatchLexer.h"

namespace rematch {

std::unique_ptr<LogicalVA> regex2LVA(std::string regex);

}  // end namespace rematch

#endif