branches:
  only:
    - wheel

environment:
  global:
    SWIG_VERSION: "4.0.2"
  matrix:
  - PYTHON: '"C:\\Python35-x64"'
  - PYTHON: '"C:\\Python36-x64"'
  - PYTHON: '"C:\\Python37-x64"'
  - PYTHON: '"C:\\Python38-x64"'
build:
  verbosity: minimal

build_script:
  - cmd: |
      "%PYTHON%\\python.exe" -m pip install --upgrade pip
      "%PYTHON%\\python.exe" -m pip install --upgrade setuptools wheel

      ECHO %PYTHON%

      7z x .\\appveyor\\swigwin-%SWIG_VERSION%.zip
      SET PATH=swigwin-%SWIG_VERSION%;%PATH%

      REM "%PYTHON%\\python.exe" setup.py build

      md build
      cd build

      cmake -DSWIG=1 -DBOOST_ROOT="C:\Libraries\boost_1_73_0" ..

      REM "%PYTHON%\\python.exe" setup.py bdist_wheel