branches:
  only:
    - wheel

environment:
  USERNAME:
    secure: rAR843Qwyh38SI4W0/DcjA==
  PASSWORD:
    secure: PG9eTxcUvb/zoFOMEbn/HA==
  global:
    SWIG_VERSION: "4.0.2"
    BOOST_ROOT: "C:/Libraries/boost_1_73_0"
  matrix:
  - PYTHON: "C:/Python35-x64"
    PYTHON_VERSION: "3.5"
  - PYTHON: "C:/Python36-x64"
    PYTHON_VERSION: "3.6"
  - PYTHON: "C:/Python37-x64"
    PYTHON_VERSION: "3.7"
  - PYTHON: "C:/Python38-x64"
    PYTHON_VERSION: "3.8"
  - PYTHON: "C:/Python39-x64"
    PYTHON_VERSION: "3.9"
build:
  verbosity: minimal

build_script:
  - cmd: |
      "%PYTHON%/python.exe" -m pip install --upgrade pip
      "%PYTHON%/python.exe" -m pip install --upgrade setuptools wheel

      ECHO %PYTHON%

      7z x .\\appveyor\\swigwin-%SWIG_VERSION%.zip
      SET PATH=swigwin-%SWIG_VERSION%;%PATH%

      REM "%PYTHON%\python.exe" setup.py build

      swig -swiglib

      md build
      cd build

      cmake -DSWIG=true -DPYTHON_VERSION="%PYTHON_VERSION%" -DBOOST_ROOT="%BOOST_ROOT%" -DSWIG_DIR="C:\projects\rematch\swigwin-%SWIG_VERSION%\Lib" -DSWIG_EXECUTABLE="C:\projects\rematch\swigwin-%SWIG_VERSION%\swig.exe" ..
      cmake --build . --config Release

      cd ..

      copy build\src\Release\_rematch.pyd python\packages\rematchpy

      "%PYTHON%\\python.exe" setup.py bdist_wheel

deploy_script:
  - ps: |
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        &"${Env:PYTHON}/python.exe" -m pip install twine
        &"${Env:PYTHON}/python.exe" -m twine upload -u ${Env:USERNAME} -p ${Env:PASSWORD} --repository testpypi dist/*.whl
      } else {
        Write-Output "No tag for deployment"
      }